### ISSUE TITLE
ConceptInstanceFinder should not return nodes from transient models

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#2101]
The ConceptInstanceFinder utility class ([node URL](http://127.0.0.1:63320/node?ref=r%3A72bc3a97-6a66-47f6-8cf2-f88ab2ada651%28com.mbeddr.mpsutil.common.model%29%2F6573709714620299069)) currently returns nodes from transient models. Usually, this is not what is required.

E.g., when running the interpreter framework after rebuilding an interpreter with transient models set to _ON_, the same interpreter will be found several times and thus each of its evaluators will be add to the list of evaluators multiple times (see [CachedInterpreterFinder](http://127.0.0.1:63320/node?ref=r%3Aea6cf71d-29d2-478d-8027-a9f4a4de53c4%28com.mbeddr.mpsutil.interpreter.rt%29%2F7441709272495082785)). In case of `tryOtherInterpreter` the same evaluator will be called multiple times.

The utility should be changed so that it will not return nodes from transient models anymore. A comment should be added to the method `findAllInstances` in order to clarify that this is the usual behavior.

**Comment by wsafonov** [comment]
The utility [method](http://127.0.0.1:63320/node?ref=r%3A72bc3a97-6a66-47f6-8cf2-f88ab2ada651%28com.mbeddr.mpsutil.common.model%29%2F6573709714620299069) from the ConceptInstanceFinder looks like it's mostly used in the interpreter context to find Interpreter definition nodes. Because it currently uses FilteredGlobalScope for the search, it also looks in transient and temporary modules. For the interpreter we don't want to look in those modules. In fact, these types of modules can be relevant only in very specific search scenarios, that's why we should exclude them from the default search in the mentioned utility method. This means we can use AllUserModelsScope, which does exactly this: excludes transient and temporary models from the search scope.
