### ISSUE TITLE
conceptdiagram doesn't play nice with Darcula theme in MPS

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#2173]
Here is an example of how a conceptdiagram (which normally looks quite readable in a Light theme) looks like in Darcula:
![image](https://user-images.githubusercontent.com/6429350/117801474-a038b500-b254-11eb-8685-ae207258339e.png)
Since Darcula is the default since MPS 2020.X, it may be good to either choose different colors or somehow make sure that better readable colors are used when a darker theme like Darcula is active.

**Comment by alexanderpann** [comment]
I think this issue should be moved to MPS-extensions, because dark themes not only affect conceptdiagrams but all diagrams (itemis.mps.editor.diagram). 
There are attributes in the stylesheet DiagramStyleAttributes that should have also defaults for the dark theme. There are also hardcoded colors for example in BasicShapeStyle.
Some hints: UIUtil.isUnderDarcula() can detect the dark theme. There is also the class JBColor, which has dark and light variants of colors.

**Comment by alexanderpann** [comment]
Implemented in https://github.com/JetBrains/MPS-extensions/pull/512.
